import { Movie } from "./moviesModel";

export const movies: Movie[] = [
  {
    title: "The Shawshank Redemption",
    year: 1994,
    genre: ["Drama"],
    director: "Frank Darabont",
    rating: 9.3,
  },
  {
    title: "The Godfather",
    year: 1972,
    genre: ["Crime", "Drama"],
    director: "Francis Ford Coppola",
    rating: 9.2,
  },
  {
    title: "The Dark Knight",
    year: 2008,
    genre: ["Action", "Crime", "Drama"],
    director: "Christopher Nolan",
    rating: 9.0,
  },
  {
    title: "Pulp Fiction",
    year: 1994,
    genre: ["Crime", "Drama"],
    director: "Quentin Tarantino",
    rating: 8.9,
  },
  {
    title: "The Lord of the Rings: The Return of the King",
    year: 2003,
    genre: ["Adventure", "Drama", "Fantasy"],
    director: "Peter Jackson",
    rating: 9.0,
  },
  {
    title: "Forrest Gump",
    year: 1994,
    genre: ["Drama", "Romance"],
    director: "Robert Zemeckis",
    rating: 8.8,
  },
  {
    title: "Inception",
    year: 2010,
    genre: ["Action", "Sci-Fi", "Thriller"],
    director: "Christopher Nolan",
    rating: 8.8,
  },
  {
    title: "Fight Club",
    year: 1999,
    genre: ["Drama"],
    director: "David Fincher",
    rating: 8.8,
  },
  {
    title: "The Matrix",
    year: 1999,
    genre: ["Action", "Sci-Fi"],
    director: "The Wachowskis",
    rating: 8.7,
  },
  {
    title: "Goodfellas",
    year: 1990,
    genre: ["Biography", "Crime", "Drama"],
    director: "Martin Scorsese",
    rating: 8.7,
  },
  {
    title: "Se7en",
    year: 1995,
    genre: ["Crime", "Drama", "Mystery"],
    director: "David Fincher",
    rating: 8.6,
  },
  {
    title: "The Silence of the Lambs",
    year: 1991,
    genre: ["Crime", "Drama", "Thriller"],
    director: "Jonathan Demme",
    rating: 8.6,
  },
  {
    title: "Interstellar",
    year: 2014,
    genre: ["Adventure", "Drama", "Sci-Fi"],
    director: "Christopher Nolan",
    rating: 8.6,
  },
  {
    title: "The Green Mile",
    year: 1999,
    genre: ["Crime", "Drama", "Fantasy"],
    director: "Frank Darabont",
    rating: 8.6,
  },
  {
    title: "Gladiator",
    year: 2000,
    genre: ["Action", "Adventure", "Drama"],
    director: "Ridley Scott",
    rating: 8.5,
  },
];
