import { Product } from "./productModel";

export const products: Product[] = [
  { name: "Laptop", stock: 10, price: 999.99, category: "Electronics", img: "../assests/product-images/laptop.png" },
  {
    name: "Smartphone",
    stock: 15,
    price: 699.99,
    category: "Electronics",
    img: "../assests/product-images/smartphone.png",
  },
  {
    name: "Headphones",
    stock: 25,
    price: 149.99,
    category: "Electronics",
    img: "../assests/product-images/headphones.png",
  },
  {
    name: "Coffee Maker",
    stock: 0,
    price: 89.99,
    category: "Home Appliances",
    img: "../assests/product-images/coffee-maker.png",
  },
  {
    name: "Desk Chair",
    stock: 12,
    price: 129.99,
    category: "Furniture",
    img: "../assests/product-images/desk-chair.png",
  },
  { name: "Monitor", stock: 20, price: 199.99, category: "Electronics", img: "../assests/product-images/monitor.png" },
  { name: "Backpack", stock: 30, price: 59.99, category: "Accessories", img: "../assests/product-images/bacpack.png" },
  {
    name: "Electric Kettle",
    stock: 18,
    price: 39.99,
    category: "Home Appliances",
    img: "../assests/product-images/electric-kettle.png",
  },
  {
    name: "Bluetooth Speaker",
    stock: 22,
    price: 79.99,
    category: "Electronics",
    img: "../assests/product-images/bluetooth-speaker.png",
  },
  {
    name: "Running Shoes",
    stock: 16,
    price: 89.99,
    category: "Footwear",
    img: "../assests/product-images/running-shoes.png",
  },
  { name: "Tablet", stock: 14, price: 299.99, category: "Electronics", img: "../assests/product-images/tablet.png" },
  {
    name: "Water Bottle",
    stock: 40,
    price: 19.99,
    category: "Accessories",
    img: "../assests/product-images/water-bottle.png",
  },
  {
    name: "Fitness Tracker",
    stock: 17,
    price: 99.99,
    category: "Electronics",
    img: "../assests/product-images/fitness-tracker.png",
  },
  { name: "Sofa", stock: 5, price: 499.99, category: "Furniture", img: "../assests/product-images/sofa.png" },
  {
    name: "Microwave Oven",
    stock: 9,
    price: 149.99,
    category: "Home Appliances",
    img: "../assests/product-images/microwave-oven.png",
  },
  {
    name: "Gaming Mouse",
    stock: 28,
    price: 49.99,
    category: "Electronics",
    img: "../assests/product-images/gaming-mouse.png",
  },
  { name: "Yoga Mat", stock: 35, price: 29.99, category: "Accessories", img: "../assests/product-images/yoga-mat.png" },
  { name: "Bookshelf", stock: 7, price: 89.99, category: "Furniture", img: "../assests/product-images/bookshelf.png" },
  {
    name: "Smart Watch",
    stock: 13,
    price: 199.99,
    category: "Electronics",
    img: "../assests/product-images/smart-watch.png",
  },
  {
    name: "Blender",
    stock: 11,
    price: 59.99,
    category: "Home Appliances",
    img: "../assests/product-images/blender.png",
  },
];
